.PHONY: help install dev build start lint clean

help:
	@echo "Frontend (Next.js)"
	@echo "  make install - npm install"
	@echo "  make dev    - next dev (port 3000)"
	@echo "  make build  - next build"
	@echo "  make start  - next start"
	@echo "  make lint   - next lint"
	@echo "  make clean  - remove .next and node_modules"

install:
	npm install

dev:
	npm run dev

build:
	npm run build

start:
	npm start

lint:
	npm run lint

clean:
	rm -rf .next out node_modules
